name: "Pull Request Docs Check"
# https://github.com/marketplace/actions/sphinx-build

on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
<<<<<<< HEAD
        #build-command: "sphinx-build -b html . _build"
        docs-folder: "docs/"
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/_build/html/
=======
        build-command: "sphinx-build -b html . _build"
        docs-folder: "docs/"
>>>>>>> 19d1756 (Add make.bat)
