name: CI

on:
  push:
    # Build on tags that look like releases
    tags:
      - v*
    tags-ignore:
      - '**a*'
      - '**-alpha'

jobs:
  sphinx-docs:
    name: Compile sphinx docs on Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        mamba-version: "*"
        channels: conda-forge,cantera/label/dev,defaults
        channel-priority: true
        activate-environment: ctwrap
        environment-file: environment.yml
    - name: Install ctwrap
      run: |
        pip install -e .
    - name: Install Sphinx dependencies
      run: |
        cd docs
        pip install -r requirements.txt
        sphinx-build -b html . _build
    - if: github.repository == 'microcombustion/ctwrap'
      name: Commit documentation changes
      run: |
        git clone https://github.com/microcombustion/ctwrap.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - if: github.repository == 'microcombustion/ctwrap'
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
